hepsi: Derle Calistir

Derle:
	g++ -I ./include/ -o ./lib/SayiNesnesi.o -c ./src/Sayi.cpp
	g++ -I ./include/ -o ./lib/BasamakNesnesi.o -c ./src/Basamak.cpp
	g++ -I ./include/ -o ./lib/SayilarListesiNesnesi.o -c ./src/SayilarListesi.cpp
	g++ -I ./include/ -o ./bin/uygulama ./lib/SayiNesnesi.o ./lib/BasamakNesnesi.o ./lib/SayilarListesiNesnesi.o ./src/main.cpp

Calistir:
	./bin/uygulama
